server:
  port: 8082

spring:
  datasource:
    name: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac
    initial-size: 5
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.by.model
